trigger:
- '*'

steps:
- task: FlutterInstall@0
  inputs:
    mode: 'auto'
    channel: 'stable'
    version: 'custom'
    customVersion: '3.0.5'
- task: FlutterTest@0
  inputs:
    projectDirectory: '.'